package hellofx.fheroes2.resource;

import static hellofx.fheroes2.system.Translate.tr;

public class MapsText {
    public static final String[] maps_messages = {
            tr("425 bottles of beer on the wall, 425 bottles of beer! If one of those bottles should happen to fall, there'll be..."),
            tr("A balanced scenario with lots of resources and land to explore."),
            tr("A bandit army of gorgons jump you without warning.  they stone your entire army demand 500 gold before they will release your comrads.  Realizing that it is much cheeper to pay then rebuild your army you part with the gold."),
            tr("Abandon All Hope!"),
            tr("Abandon All Hope Ye That Enter Here"),
            tr("A bit of crystal!"),
            tr("A bit of mercury!"),
            tr("A bit of sulfur!"),
            tr("Above you looms the ancient Ice Palace.  Dimly remembered myth speaks of a Prince who rejected the advances of the Winter Goddess, and thus he and his domain were cursed to remain shrouded in ice, hidden in a forgotten corner of the world.  It is said that he can only be rescued by a hero who is both clever and bold.  Are you that one?  Do you dare enter this frozen domain?"),
            tr("A cache of crystal!"),
            tr("A cache of gems!"),
            tr("A cache of gold!"),
            tr("A cache of mercury!"),
            tr("A cache of sulfur!"),
            tr("A chance to end a bitter war has finally arrived as a new resource-laden land has been discovered."),
            tr("A chunk of gold!"),
            tr("A chunk of ore!"),
            tr("A couple of gems!"),
            tr("\"Act of Desperation\""),
            tr("A desert isle rich in resources rewards the quick.  Just be sure to watch your back!"),
            tr("A dolphin playfully jumps into the air."),
            tr("A Dragon, A Cyclops, or an Undead. King of the Centaurs, His name is ....?"),
            tr("A flight of dragons circles overhead."),
            tr("A flock of seagulls circle overhead."),
            tr("A friendly dolphin splashes alongside the ship."),
            tr("After a long search of the island, I have discovered that there is no way for me to escape without help.  I can not steal a ship from one of the coastal castles, and I dare not venture into the desert unless I wish to become Dragon food.  Should anyone find this, I beg of you, please send a ship and get me off this cursed island!  -Sir Christian"),
            tr("After centuries of friendship, the Wizards have suddenly decided to stop sharing their Library with the rest of the world.  This can't be good!"),
            tr("After many years of peace, you discover that your sworn enemy from across the sea has chosen to invade your homeland by raising up the ocean floor to bridge the distance! You must not let them gain a foothold on this continent, in fact, your King has ordered you to establish a foothold on theirs!  To make matters worse, two of your OWN towns have thrown in their lots with the enemy..."),
            tr("After you return from a scouting trip, your Seneschal hurries to greet you.  \"My Lord, in your absence I signed an agreement in your name with a Master Merchant.  If we supply him with the resources he needs, through trading, he can return the resources to us in a week or so, plus some additional ones.\"  The Seneschal eyes you anxiously.  You hesitate, then nod slowly, \"Good, we can use more resources>\""),
            tr("A ghostly pirate ship appears and sails on by."),
            tr("A Gift from your King, and a note that reads \"Use these resources wisely, It's all we have left\"."),
            tr("A gift of gold, m'lord, from the people of Enroth, to the people of Enroth.  Good luck, and may God save true King Roland!"),
            tr("A glint by a tree catches your eye..."),
            tr("A gold cache!"),
            tr("A gold chunk!"),
            tr("A gold nugget!"),
            tr("A great Black dragon stands before you. It speaks in a surprisingly soft voice, saying, \"The elves believe they have sent another hero to reclaim their prize. I believe they have sent me another meal.\""),
            tr("A group of peasant farmers approaches you, \"We are in dire need of your assistance.  Our castle to the north has been overrun and our Lord killed.  Please help us regain our homes!  There are still women and children there!  Take what we have to help!\""),
            tr("A group of peasant farmers approach you, \"We are in dire need of your assistance.  Our castle to the east has been overrun and our Lord killed.  Please help us regain our homes!  There are still women and children there!  Take what we have to help!\""),
            tr("A group of peasant farmers approach you, \"We are in dire need of your assistance. Our castle to the east has been overrun and our Lord killed. Please help us regain our homes! There are still women and children there! Take what we have to help!\""),
            tr("A group of peasant farmers approach you, We are in dire need of your assistance.  Our castle to the northeast has been overrun and our Lord killed.  Please help us regain our homes!  There are still women and children there!  Take what we have to help!\""),
            tr("A handful of gems!"),
            tr("Ah, you stumble across something buried in the sand.  As you dig it up you discover a small pile of gems and crystal."),
            tr("A Knight and Necromancer team up against the Barbarian and Sorceress. (Blue and Green vs Red and Yellow)"),
            tr("Alamar"),
            tr("A large contingent of the king's guard approaches you.  \"Ahh, we have finally caught up to you.  The king requires tribute from all of his vassals and you have been negligent far too long.\""),
            tr("A large map with lots of resources and treasure. Exploration and victory will require many heroes."),
            tr("A legion of peasants stands between you and this unclaimed island."),
            tr("Algary"),
            tr("A little bit closer..."),
            tr("All mines are grouped by type. Trade is your only hope."),
            tr("A lump of crystal!"),
            tr("A lump of gold!"),
            tr("A lump of mercury!"),
            tr("A man appears from behind the sand dune. \"At last,\" he says, \"Someone has come to rescue me! I am forever grateful. Alas all I have to offer you in return are these souvenirs from my wrecked ship.\""),
            tr("A man is laying on the ground, near death. He looks to you and speaks, \"Please help my companions! Please... they can't...cough...get away from...cough...the drag...\" With that, he dies."),
            tr("A merchant caravan arrives, bringing gold and supplies, however, no one can seem to remember where they came from.  You silently praise this anonymous benefactor and continue your duties."),
            tr("a mirror"),
            tr("An albatross flies ahead of the ship for a while"),
            tr("Anduran"),
            tr("An enemy from across the sea has seized half your towns.  Can you put aside your own feud with your brother to fight this common enemy?"),
            tr("\"Annexation\""),
            tr("An old elf is sitting on a rock in a glen, pounding on the shackles on his feet with a stone. You help him remove them and ask him his tale. \"I'm a deserter from Drakonia's army. She has enslaved all the elves to support her madness. She must be stopped.\" Then he slips into the woods without a sound, leaving behind just his cloak."),
            tr("Antioch"),
            tr("A piece of crystal!"),
            tr("A pile of crystal!"),
            tr("A pile of gems!"),
            tr("A pile of gold!"),
            tr("A plague of undead is upon us. Who will unite the living against the dead?"),
            tr("\"Apocalypse\""),
            tr("A quantity of crystal!"),
            tr("A quantity of mercury!"),
            tr("A quantity of sulfur!"),
            tr("Archibald"),
            tr("Archibald has also sent an army to find the Crown, you must find it first or all is lost."),
            tr("Archibald is hiding at the end of the river."),
            tr("A resource rich valley keeps the Wizard and the Necromancer apart. Your opponent's army will arrive in 3 months so hurry."),
            tr("Arm of the Crusader"),
            tr("Arm of the Cyclops"),
            tr("Arm of the Dragon"),
            tr("Arm of the Phoenix"),
            tr("Arm of the Titan"),
            tr("Arr' Here be pirates gold buried."),
            tr("A shipment of wood has arrived from your kingdom!"),
            tr("A splash in the seaweed alerts you to a mermaid waving in a friendly manner. \"Oh, I thought you were Ahab.\" She is surprised, but quickly composes herself. \"Well, if you meet him, give him these treasures I have collected.\""),
            tr("Assassins tried to kill our ally."),
            tr("Astircaer"),
            tr("A stranded Wizard with only a small force must conquer an entire continent of hostile forces."),
            tr("A supply ship has arrived from the homeland!  You send word home that all is well."),
            tr("As you approach the barrier, you see the old elf you helped free. This time, however, you see that he is wearing a cape of fine weave, and a wooden crown is on his head. He sees your forces, and says \"Take this sword, and with it, strike down Drakonia and help free my people.\" The old elf then strides regally into the woods."),
            tr("As you approach the gates of the Ice Palace, one of your troops points in terror.  You watch in awe as great slabs of ice separate from the castle walls with loud cracking reports and crash to the ground.  Soon the ice is gone and the sun begins to peak through the gloom.  The deathly silence that must have ruled these lands for centuries ends as birds begin to sing.  From inside you hear the sounds of life."),
            tr("As you approach the tent, the leader of the nomads comes out to greet you. He says, \"It was prophecied many years ago that a great hero would come to greet us in our sacred valley, and we would prosper afterwords. Now it has come to pass, and we offer you these gifts as tokens of our thanks.\""),
            tr("As you approach,  you hear whispered mentions of \"the wild barbarian who passed this way months before\". One of the villagers approaches you and hands you an object, saying \"The wild one dropped this. You must be his kin. Therefore I give it to you. But beware! Many in the village will not be as friendly as I.\""),
            tr("As you break your fast your sage rushes in, \"Good news, my lord!  I have translated the message.  Two great heroes were imprisoned many years ago.  They lie sleeping - still guarded by magic barriers and monsters.  My lord, they lie nearby- in between our ally and us.  If we could free them, they would surely aid us against our enemies!  The password to the first magic barrier can be learned at the Aqua Traveller's Tent.\""),
            tr("As you enter the small clearing, you see a familiar figure talking to a group of halflings and soldiers. You stay awhile and listen to his speech. \"The time to throw off these chains of tyranny is now! We must strike at the heart of her empire, and destroy the evil that she has brought to our land.\" As the old elf finishes speaking, he gets up from his mossy seat and once again, blends into the woods with incredible grace."),
            tr("As you lay down to nap after a long battle, you notice a lucky four-leaf clover."),
            tr("As you make  your way through the last of the golemn debris, a group of halflings runs towards you carrying fruit and flowers. \"Thank you so much!\" Their leader exclaims, \"We've been trapped in here for ever! Come by our homes, we'll pack up and go with you!\""),
            tr("As you make your way to the shrine, some very thin and hollow-eyed men come out of the flower patch and stare at you.  Seeing that you want the gold, one of them says to you \"Hey, man, if you're, like, so lusty for earthly wealth, then, like, have this too.\" You graciously take what they have offered and back out of the clearing."),
            tr("As you prepare your lands to fight the onslaught from the South, a curious message appears on your table in the Great Hall of your Castle.  Written in some ancient language, none but your sage can make any sense of it.  She promises to have the words deciphered by tomorrow..."),
            tr("A three hour tour, a three hour tour..."),
            tr("A tiny gnome points to a chunk of crystal you otherwise would have overlooked!"),
            tr("Atlantium"),
            tr("At last, the king is dead.  For years you have planned his demise, but now it is done, and there is no heir to take his place, though the Knights to the south believe that they are the rightful successors.  A wealth in wood (to the south) and ore (in the northern mountains) provides you with trade goods, and your isolation has allowed you to prepare your forces of darkness for this day.  Go, now, and fulfill your destiny!"),
            tr("At the base of the mountain you see something that glitters.   You discover an ancient pile of offerings to the gods."),
            tr("Avalon"),
            tr("Avone"),
            tr("A wild magic has allowed a bridge to form between two lands...  Your one hope is to capture castle \"Black Fang\"."),
            tr("Barbarian's castle lies to the south."),
            tr("Barbarians from the north threaten all civilization. Can you repel the hordes?"),
            tr("\"Barbarian Wars\""),
            tr("Barrowton"),
            tr("Basenji"),
            tr("Bayside"),
            tr("Baywatch"),
            tr("Because the Darkscale Valley is so barren, the Emperor will be sending wood to you every week. Use it wisely, for it is all you shall have."),
            tr("Before questing for the orb of negation, you must first crush the local opposition. After the Sorceresses are removed from the earth, go east where legend says the orb lies.  You may expect a convoy of supplies in a week or so to aid your conquest."),
            tr("Before you may pass, the spirit guardian of this valley demands tribute."),
            tr("Being held...."),
            tr("Beltway"),
            tr("\"Betrayal!\""),
            tr("Beware -- Entering Hyrda Country"),
            tr("Beware for whom the bell trolls."),
            tr("Beware of Pirates!"),
            tr("Beware of thieves!"),
            tr("Beware of traps ahead."),
            tr("Beware of Warlocks"),
            tr("Beware the deadly swamps!"),
            tr("Beware the Domain of Dragons"),
            tr("Beware the Dragon Leader"),
            tr("Beware the edge of the world!"),
            tr("Beware the moors and stick to the roads."),
            tr("Beware the rocks"),
            tr("Beware the sirens!!!"),
            tr("Beware the sirens!"),
            tr("Beware the whiporwill..."),
            tr("Beware, the whirlpool may not take you into a friendly embrace."),
            tr("Beyond here be Dragons!"),
            tr("Beyond the door, there be Dragons. BEWARE!"),
            tr("Big Oak"),
            tr("Blackburn"),
            tr("Blackfang"),
            tr("Black Fang"),
            tr("Black Oak"),
            tr("Blackridge"),
            tr("Blacksford"),
            tr("Black Vein"),
            tr("Blackwind"),
            tr("Bloodreign"),
            tr("Boats my be needed to access some parts of this peninsula."),
            tr("Boats Sold Here            Inquire Within"),
            tr("BoneVille"),
            tr("Borderlands"),
            tr("Bridge out!"),
            tr("Bridge Out!"),
            tr("Brindamoor"),
            tr("Broken Alliance"),
            tr("Brownston"),
            tr("Buried Treasure!"),
            tr("Burlock"),
            tr("Burton"),
            tr("Capture the necromancer's dreaded castle \"Death Gate\" and free the land from the undead plague."),
            tr("Capture the town on the island off the southeast shore in order to construct a boat and travel back towards the mainland."),
            tr("\"Carator Mines\""),
            tr("Cathcart"),
            tr("Ceallach"),
            tr("Chandler"),
            tr("Chilton"),
            tr("Chronos"),
            tr("Come and...."),
            tr("Compared to the rest of the villages in this land, this village seems grand, but in any other land it would seem poor. From here you can see the tall spires of the Warlock's tower of Dragons."),
            tr("Complete"),
            tr("Condemned!"),
            tr("Congratulations! After navigating the treacherous coast, you have established trade between the north and south."),
            tr("Corackston"),
            tr("Corlagon"),
            tr("\"Country Lords\""),
            tr("Crossroads"),
            tr("Crossroads North"),
            tr("Crossroads South"),
            tr("Dainwin"),
            tr("Danger a whirlpool destroyed my ship."),
            tr("Danger, Dragons abound!"),
            tr("DANGER!  QUICKSAND!"),
            tr("Danger! Troll bridge ahead!"),
            tr("Danger - Turn Back Now"),
            tr("Dark clouds loom overhead as you enter this valley."),
            tr("Dead Pine"),
            tr("Dear Diary,                           I found a mermaid today.  She was floating in a patch of seaweed next to a rock.  A very friendly sort of creature too!  Gave me all sorts of lovely gems and jewelry!  She said to come back again sometime for more of the sea riches.  Wow. Ahab"),
            tr("Deathgate"),
            tr("DeathGate"),
            tr("Decisions"),
            tr("\"Defender\""),
            tr("Destroy the Barbarians who are attacking the southern border of your kingdom! Recover your towns and then invade the jungle kingdom."),
            tr("Detour! Mountain pass to the East has been known to have avalanches! For your own safety, follow the road South."),
            tr("Detour! Troll bridge ahead!"),
            tr("Dirt"),
            tr("DirtWater"),
            tr("Dominion"),
            tr("Do Not Enter!"),
            tr("Do not remove coins from fountain."),
            tr("Dragadune"),
            tr("Dragonburg"),
            tr("Dragon City"),
            tr("Dragon City lies beyond the Scorpion Hills."),
            tr("Dragon Hill"),
            tr("\"Dragon Master\""),
            tr("Dragon Rider"),
            tr("Dragons Everywhere!"),
            tr("Dragon's Eye"),
            tr("Dragontooth"),
            tr("Dragon Town"),
            tr("Dragonville"),
            tr("Dragon Wars"),
            tr("Dragon Watch"),
            tr("Drakonia"),
            tr("Drakoran"),
            tr("Dwarfhall"),
            tr("Dwarfhall, Domain of the dwarf King."),
            tr("Dwarf Hall, domain of the dwarf King."),
            tr("Eatio"),
            tr("Edgewood"),
            tr("Elk's Head"),
            tr("Elowyn"),
            tr("Enroth"),
            tr("Entering high in the desert"),
            tr("Entering Praires of the Middlelands"),
            tr("Entering the desert high"),
            tr("Entering the high desert"),
            tr("Entering the higher desert"),
            tr("Entering the Valley of Magic"),
            tr("Erliquin"),
            tr("Evil Igor"),
            tr("Fadlan"),
            tr("Fantasy Island."),
            tr("Farlien"),
            tr("Federal express, when it absolutely positively has to be there turn one."),
            tr("fedx comp"),
            tr("Fedx for comp"),
            tr("Fenton"),
            tr("Fetid Elm"),
            tr("Final message from Overlord. \"The royal executioners are on their way. My gold, the land or your head- it's your choice.\""),
            tr("Find and defeat the Pirate Leader!"),
            tr("Find and destroy the evil beings who rule the wastelands."),
            tr("Find the center island."),
            tr("Find the Ultimate Artifact and be proclaimed King, or smash the opposition and take control."),
            tr("Find Your Wayward Son who is rumored to be living in the desolate lands. Do it within 8 weeks or it will be of no help to your family."),
            tr("Fire King"),
            tr("\"First Blood\""),
            tr("Five heroes vie for control of a familiar land."),
            tr("Fool's Gold"),
            tr("For a total of 400,000 gold your opponents will become \"loyal\" subjects, otherwise... let them eat cake!"),
            tr("For centuries, the Wizards of the North have maintained a vast library for all the world to share.  Now, however, they have closed their doors, and issued declarations of war to each of the other rulers of the land.  To make matters worse, rather than ally with you to face the Wizards, each of the others have decided to go forth on their own in an effort to conquer this land for themselves!  Prepare your forces, commander, for you now stand alone."),
            tr("\"Force of Arms\""),
            tr("For decades you have studied, learned, and allowed yourself to be ruled by that pitiful excuse for a king, knowing that one day the time would come for you to sit on the throne.  That time is now, for the king is dead and without an heir.  You have the advantage of isolation from the rest of the kingdom, but beware the miles of coastline that could leave you vulnerable to attack.  Go, now, and wipe your enemies from this land!"),
            tr("Forder Oaks"),
            tr("Forestria"),
            tr("For Honor"),
            tr("For information about Ye Rich lands to the south, speak to Alponse at the Golden Goose Tavern. Excellent views, plentiful water."),
            tr("Forsaken Lands"),
            tr("For sale."),
            tr("Fortress Isle"),
            tr("For years, you have existed peacefully in the Forest of Dreams, knowing that your king was the kindest and strongest ruler the land had seen in centuries.  Now, however, his reign is at an end, and there is no heir to succeed him.  You realize that a power struggle is coming, and that you must brace yourself for war, and prevent those who would harm this land from coming into power!"),
            tr("For years, you've been able to keep your subjects \"appeased.\"  Now however, you discover not only that your entire kingdom has turned against you, but most of your outer towns have fallen to the different factions.  To make matters worse, all your gold suddenly seems to be missing from the treasury!"),
            tr("Fountainhead"),
            tr("Four kingdoms race to capture the island of Sharkania."),
            tr("Four lakes have castles, three have treasure."),
            tr("Four players must work together to assault the Wizards' Stronghold."),
            tr("Frozenpeak"),
            tr("Full House"),
            tr("Gain the aid of the elves. They will not allow trees to be chopped down, so we will send you wood every 2 weeks. You have 7 months!"),
            tr("Gallavant"),
            tr("Galveston"),
            tr("Garamok"),
            tr("Gate"),
            tr("Gate to the Isle of Knowledge"),
            tr("Gate to The Isle of Knowledge"),
            tr("Gaurdian"),
            tr("Gavonshire"),
            tr("Giants"),
            tr("Glastonbury"),
            tr("Go away!"),
            tr("GO AWAY!"),
            tr("Goblin Island"),
            tr("Goblin King"),
            tr("Go Home!"),
            tr("Go north to find the lost gold-mine."),
            tr("Good vs. Evil"),
            tr("Gorgomar"),
            tr("\"Greater Glory\""),
            tr("Greed"),
            tr("Green bonus stuff"),
            tr("Green gets stuff"),
            tr("Greenroot"),
            tr("Green's Allowance"),
            tr("Green's Groceries"),
            tr("green stuff"),
            tr("Green stuff"),
            tr("Greywind"),
            tr("Grim"),
            tr("Grrr, Blazzer, Grrupt. Be gone with you!"),
            tr("Guardian War"),
            tr("Gungtooth"),
            tr("Hail Unicorns!"),
            tr("Hampshire"),
            tr("Have fun storming the castle!"),
            tr("Havenwood"),
            tr("Hawkins"),
            tr("Help!"),
            tr("Help me...."),
            tr("Help peasant farmers regain their castle and land, else they'll take your crops."),
            tr("Hero's Hall"),
            tr("High in the snowy crags, you meet an old witch who, in return for a trinket of yours, gives you a powerful magical object she used to use as a footstool before she was exiled into the mountains by her own townspeople."),
            tr("Hillstone"),
            tr("Hilltop"),
            tr("Hilltown"),
            tr("Horizon"),
            tr("Hot Spot"),
            tr("Hungry dragons await.  Welcome, food."),
            tr("Hurry, no time to wait.  This way to the dock."),
            tr("Hurry up! Few days are left before the enemy's army arrives."),
            tr("I am...."),
            tr("I am one of the few remaining survivors of the wrecked pleasure ship, Exhorbitance. I think we'll all be dead of hunger soon, for we are out of caviar. We ate the chef yesterday."),
            tr("Ibn Fadlan"),
            tr("Ice Palace"),
            tr("Ice Prince"),
            tr("Icy lands ahead."),
            tr("I didn't do it!"),
            tr("If three heroes could dig six holes in three days, how long would it take six heroes to dig twelve holes?"),
            tr("If you free a hero, they may help..."),
            tr("If you value your lives, for God's sake, Don't go through this whirlpool!"),
            tr("Income for Yellow."),
            tr("In the hole you find a chunk of ore!"),
            tr("In the stream you find an old compass!"),
            tr("In this glen live some very naughty halflings. Stay Away!"),
            tr("In two more weeks, if you have not located Joseph, your kingdom will surely lose its current battle with Harondale."),
            tr("I see you, you see me."),
            tr("Is it something I said? Go back and I will forget the whole thing."),
            tr("IslandHome"),
            tr("Island of the Elves"),
            tr("Island of the meek"),
            tr("Island of Wolcott"),
            tr("Isle Maze"),
            tr("Isle of Knowledge"),
            tr("It has become apparent that if all your enemies were eliminated, you would have all the time you need to find the Ultimate Artifact."),
            tr("It is obvious that the mage that once was here had won many battles!  There, upon his hand, is a most powerful ring!"),
            tr("It is rumored that a bridge of land used to exist between the two continents, but that a wild magic caused it to sink into the sea, taking with it all those who used to inhabit it.  To try to raise this bridge is to invite a curse upon the world!  The spirits of the dead will haunt us all!"),
            tr("It is said that King Zealot found the gods' artifact once and it let him rule for 100 years."),
            tr("It looks like there used to be an ore mine here but all you see now is a hole in the ground and some minerals scattered around."),
            tr("It's a battle for supremacy as the Blue and Green heroes take on Red and Orange in team competition!"),
            tr("It's windy at the top.  Defend, Divide, and Conquer."),
            tr("IvanHome"),
            tr("Ivan lives in the desert."),
            tr("Ivory Gates"),
            tr("I, Wilgatus, besiege you - do not fight me for I am all powerful and will destroy you if you persue me.  I will demonstrate my power."),
            tr("I Would Go That Way If I Were You."),
            tr("Jarkonas"),
            tr("Jarkonas VI"),
            tr("Jolly Roger was here"),
            tr("Joseph"),
            tr("Jungomar"),
            tr("Just 30 days left!"),
            tr("Just ONE week left!"),
            tr("Kalindra"),
            tr("Kastor"),
            tr("Keep going south"),
            tr("Keep Off The Grass!"),
            tr("Keep Out!"),
            tr("King John"),
            tr("King of Death"),
            tr("Knight's Trail."),
            tr("Knight stuff"),
            tr("Lakeside"),
            tr("Land's Edge"),
            tr("Land teleporters will get you to your destination sooner."),
            tr("Lankershire"),
            tr("Lavalor"),
            tr("Like, Stuff And Junk?"),
            tr("Living on the outskirts of the kingdom, you are considered an unwelcome outcast by the other leaders of the realm, though you always showed your support for the king.  Now, however, the king is dead, and many of those who spoke out againt him seek to seize his throne for themselves.  You have a vast desert at your back, rich with gems, and the advantage that many do not consider you a threat.  Go, now, and show them how wrong they are!"),
            tr("Lladner Dock"),
            tr("Log go up... Log go down... Log go up... Log go down...  OOoohhhhhhhh........"),
            tr("Lombard"),
            tr("Long live Roland the true King!"),
            tr("Long live Roland the true King."),
            tr("Look before you leap."),
            tr("Look out!"),
            tr("Lord Alberon"),
            tr("Lord Alberon calls you into his war room. He says, \"I am glad you have chosen to remain loyal to me, but this war is a terrible one for my kingdom. Already, the sorceress' towns to the Northeast have become unsure about their loyalties, and will not pledge allegiance to either side. This is hard on our cities as most of the wood in the land comes from these towns. We will need to recover their sawmills and take their towns by force.\""),
            tr("Lord Haart"),
            tr("Lord Halton"),
            tr("Lord Kreager"),
            tr("Lord, messages have begun pouring in from our spies in the other island courts.  They have learned of a new volcanic island with vast amounts of reasources.  Your Majesty, with these new reasources we could put an end to a century of war between the islands, and reunite them under your rightful rule."),
            tr("Lost Continent"),
            tr("Lost Gold- Mine"),
            tr("Lost Island."),
            tr("Lost Relic"),
            tr("Maelstrom of Deceit"),
            tr("Maelstrom of Misery"),
            tr("Magic"),
            tr("Magic Three"),
            tr("Many dust plumes rise from the floor of this small valley. You see various bands of nomads roaming about, and in the distant, the bright flames of their camp."),
            tr("Many guardians stand between you and your enemies, but anybody can sneak through the back door!"),
            tr("Many that have gone through this door have never returned."),
            tr("Many years ago, a couple of mages had a \"duel\" that forever changed the lake at the center of this continent.  Hearty adventurers might find interesting treasure there!"),
            tr("Many years ago, a falling star crashed near here.  Only now the area is safe enough to explore.  Rumor has it a castle exist where the star fell."),
            tr("Many years ago, your father, the King, died in a freak hunting accident.  Since then, you and your brother have jointly ruled his kingdom, but both of you have been seeking a way to seize the throne for yourself.  You got your wish.  Attackers from across the sea have captured more than half your towns and castles, effectively dividing the continent in two.  Now is the time to repel these invaders and do away with your brother once and for all!"),
            tr("Marco"),
            tr("Marsh Home"),
            tr("Martine"),
            tr("Mayland"),
            tr("Meramec"),
            tr("Message from Archibald. \" Do not dare to return without my Crown.\""),
            tr("Message from Archibald. \" General, thank you for bringing me this lovely gift. I have decided to participate directly in the capture of my brother Roland. Since your military advice has taken us this far, I will follow your orders to the letter.\""),
            tr("Message from Overlord. \"STILL WAITING FOR MY GOLD!\""),
            tr("Message from Overlord. \"WHERE'S MY GOLD?\""),
            tr("Message from Roland. \"General, circumstances permit me to take a hand in the events of this final conflict. I have your spoils of war with me and I will follow your advice explicitly.\""),
            tr("Message from Roland.  \"General, I have sent most of our troops and material ahead to the region of the final conflict with Archibald.  Unfortunately, Lord Corlagon has cut us off from the rest of our army.  I will be awaiting your victory in a castle across the west river.  I should be safe from attack.\""),
            tr("Message from Roland. \" We cannot hope to defeat Archibald without the Crown, I'm counting on you.\""),
            tr("Middle Gate"),
            tr("Middleton"),
            tr("Middletown"),
            tr("Might vs. Magic"),
            tr("Mineral Wars"),
            tr("Mirkosov"),
            tr("mirror"),
            tr("Money For Red"),
            tr("MONEY, MONEY, MONEY!"),
            tr("Morale becomes even lower as the endless cliffs move past."),
            tr("More water than land, you'll still spend lots of time on foot as you search a literal horde of islands."),
            tr("Mountain king"),
            tr("Mountainview"),
            tr("Mr Ed"),
            tr("Mr. Yellow's Income"),
            tr("Murray's resort Isle!"),
            tr("Mutiny!  The crew has dumped off my precious cargo into the sea!  Thank goodness it floats - when I've rid of them, I'll come back to pick it up!"),
            tr("My leige, our scouts report three other lords are attacking from the south. They work in conjuction with each other to eliminate us! We must keep this castle and remove the threat of the enemy. We wish you luck!"),
            tr("My leige, we have established a foothold (which we cannot afford to lose) and all of our Heroes have joined us. The king has made us the offer to purchase this land for 200,000 gold or we may take it by force. The local lords have been fighting and each wants to be the one that defeats us. Now all the local armies have arrived on the beach, creating a state of complete Pandemonium!"),
            tr("My Treasure Is Buried Beneath Three Palm Trees"),
            tr("\"Necromancers!\""),
            tr("New Dawn"),
            tr("New Enemies"),
            tr("New Vertigo"),
            tr("Nightshadow"),
            tr("No Description"),
            tr("No Fishing!"),
            tr("No gems, crystal, or mercury for red."),
            tr("None of the four leaders like being stuck in a land that has only one season."),
            tr("NO, Not That Way. This Way."),
            tr("No one has ever made it out of the deadly swamps alive!"),
            tr("Noraston"),
            tr("North Road"),
            tr("North vs. South"),
            tr("No stuff for red"),
            tr("No sulfer fer Yella."),
            tr("No swimming."),
            tr("Notice- Those who put messages in bottles will be tortured."),
            tr("No Trespassing"),
            tr("No tresspath...  No tree...  No thresh...  GO AWAY!"),
            tr("Now leaving Swamplands of the Eternial"),
            tr("Obsidian"),
            tr("Of the necromancers...."),
            tr("Ogrehild"),
            tr("Olympus"),
            tr("One of the seers in your castle comes to you in the morning with urgent news. Your one time comrade, the wizard Joseph, and his armies have been imprisoned in a jail nearby. His power would surely aid you in your quest to reclaim the library, you think to yourself. Perhaps there is a way to rescue him..."),
            tr("One of your aides reports that the Castle of Farlien is located on the northeast spur of this island, and is a stronghold for the enemy. He urges you to take it out as soon as possible, and then move onto other islands."),
            tr("One of your \"allies\" has joined Archibald.  You now face an opponent with three castles to your one.  Good luck!"),
            tr("One of your \"Allies\" has joined Roland. You are now facing three castles, all belonging to the enemy. Good luck!"),
            tr("One of your loyal goblins has brought you an armload of crystal!"),
            tr("One of your loyal subjects, a fairy tells you where to find a cache of mercury!"),
            tr("One of your scouts reports a tiny cave nearby. Upon investigating, you discover a small cache of goods. In the dirt by them is etched 'Ivan'."),
            tr("One of your troops stubs its paw on something buried here.  After a few hours of digging you unearth a cache of treasure!"),
            tr("Only a month remains in which to find Joseph."),
            tr("On quite days, Nubbie the sea monster can be seen!"),
            tr("Orange stuff"),
            tr("Orcville"),
            tr("Ostoroth"),
            tr("Other than the dragons, the elves don't have any enemies."),
            tr("Our ally was greatly weakened when his resources were plundered."),
            tr("\"Our Finest Hour\""),
            tr("Our reinforcements were lost in a storm, we salvaged all we could!"),
            tr("Our spies have discovered that the barbarian hordes are now receiving support from kraeger! You must hurry and find the third piece before your forces here are crushed!"),
            tr("Overlord"),
            tr("Pandemonium"),
            tr("Paper can gain you what wood and sail cannot."),
            tr("Password found by Crystals to the South."),
            tr("Peacekeeper"),
            tr("\"Peasants!\""),
            tr("Peasants"),
            tr("Peasantsville"),
            tr("Perenor"),
            tr("Pet Cemetary"),
            tr("Pick one of four Knights in this large and inhospitable land."),
            tr("Pig's Eye"),
            tr("Pinehurst"),
            tr("Pirate Cove"),
            tr("Pirate's Cove"),
            tr("Pirate Utopia"),
            tr("Pirites strike and take the gold from you holds."),
            tr("Pixie"),
            tr("Play the Knight or Barbarian in an alliance in this classic duel against the four spell casters. (Blue and Green vs Red)"),
            tr("Please...."),
            tr("Plenty of resources and lots of ground to cover. Watch out for Orange and Purple!"),
            tr("Portals"),
            tr("Portsmith"),
            tr("POSION - DO NOT DRINK"),
            tr("Powerful magic lies southwest of here in the Valley of the Kings."),
            tr("Prisoner on...."),
            tr("Pyramid"),
            tr("Quick Silver"),
            tr("Raste"),
            tr("Realm of the Undead.  Fresh blood welcome."),
            tr("Red bonus"),
            tr("Red player sympathizes with the undead cause."),
            tr("Red's Connection"),
            tr("Redshield"),
            tr("Red's Lunch Money"),
            tr("Red's Rubles"),
            tr("Red stuff"),
            tr("Regrettably, you have no castle with which to begin your assault. Fortunately, however, Kraeger's forces are weak here in the south, and you have bribed a rebel necromancer to aid you in the beginning of your conquest."),
            tr("Reinforcements have arrived, Gold from the homelands!"),
            tr("Remains of a long since dead wizard have attracted an ancient artifact.  This artifact has now attached itself to you!"),
            tr("Remember, you're searching for the Ultimate Artifact... don't get distracted!"),
            tr("Rendall Koski was here. 1997.  Northampton, Massachusetts There is a powerful artifact in the southeastern corner of the world.  Go for it, explorer!"),
            tr("Reports from your spies tell of enemies on the march.  As you rush to the castle courtyard to prepare your armies, you are intercepted by your Chaplain.  \"My Lord, I have received word that we should send what Heroes we can to the Isle of Knowledge.   The Scholars there have agreed to teach them so they will be strong for the battles ahead of us.\"  You thank the Chaplain for the information and head thoughtfully into the courtyard."),
            tr("Rescue your crazy Uncle Ivan. Find him within 4 months or it will be no help to your kingdom."),
            tr("Restricted Area, Do Not Enter!"),
            tr("Rest stop."),
            tr("Retake the Castle of Ivory Gates."),
            tr("Revolution"),
            tr("Right thinking - he who takes the riskes deserves the rewards."),
            tr("River Crossing"),
            tr("Road Ends"),
            tr("Road to Isle of Knowledge"),
            tr("Road to the Isle of Knowledge"),
            tr("Robbers have looted your treasury and you have lost valuable resources."),
            tr("Robbers have looted your treasury, stealing valuable resources."),
            tr("Roc Haven"),
            tr("Rogar"),
            tr("Roland"),
            tr("Roscomon"),
            tr("Rotten Birch"),
            tr("Rumors abound and your faithful hero Sandro is now highly regarded by the masses. Should Sandro desert you, all will be lost."),
            tr("Sandcaster"),
            tr("Sandro"),
            tr("Sands of Time"),
            tr("Sansobar"),
            tr("\"Save the Dwarves\""),
            tr("Scabsdale"),
            tr("Scorched Earth"),
            tr("Scouts have reported a town to the North.  They have also heard some disturbing news.  Their seems to be a war raging in this area."),
            tr("Scouts report the enemy's stronghold lies to the Southwest. Our swift arrival has caught them by surprise. If you move quickly their resistance will be minimal."),
            tr("Scouts report the notorious necromancer \"Wyrm\" has been sighted to the northeast."),
            tr("Scummy"),
            tr("Searching in the dust of this abandoned campsite, you find a magic scroll."),
            tr("Seasons Change"),
            tr("Secret Mountain Pass"),
            tr("Seek out the Ultimate Artifact to be victorious in this strangely shaped land."),
            tr("Seek the great library, for only with the guidance of the musty tomes therin will you find the means to reveal and bind the fount to your will."),
            tr("Seven Lakes"),
            tr("Sharkania"),
            tr("Sheltemburg"),
            tr("Sherman"),
            tr("Shipwrecked!"),
            tr("Should this message ever reach home, please know that this has become a hostile place since the King's death.  No less than six factions are at war with each other, each seeking to be the King's successor.  Beware especially of the Barbarians and the Necromancers who control the north, their regions are easily defended and they have a wealth of gold and gems.  Do not venture to this land without a sizeable force.  -Sir Christian"),
            tr("Sirein"),
            tr("Six factions have established a foothold on a huge, unexplored continent.  Can you eliminate the other five?"),
            tr("Six heroes with large armies prepare to slug it out for total domination!"),
            tr("Skirmish"),
            tr("\"Slay the Dwarves\""),
            tr("Slippery when wet."),
            tr("Slugfest"),
            tr("Snagged on a thorny bush, you discover a scrap of cloth. The design on it looks like the coat of arms of Ivan's house!"),
            tr("Snowdrop"),
            tr("Somebody has stuffed a pile of gems in the ditch!"),
            tr("Some crystal!"),
            tr("Some gems!"),
            tr("Someone has stolen 100 wood and 77 ore from you. Ah, that's nothing. Let's keep going."),
            tr("Someone has stolen gold and resources from  the palace treasury!  You suspect your enemies, but you can't know for certain."),
            tr("Someone is playing a pan flute around here."),
            tr("Someone notices a piece of parchment lying behind a clump of grass. You pick it up. It looks to be a page from a journal, and it reads, \"...made it past the first guardians. Hopefully will reach the ancient desert city soon. Only hope my forces are strong enough to survive...\""),
            tr("Some ore!"),
            tr("Some sulfur!"),
            tr("Some unlucky adventurers have been captured and imprisoned in these lands."),
            tr("Sorceress Forest.  Show respect for nature!"),
            tr("Sorpigal"),
            tr("South Mill"),
            tr("So you think you're smart?"),
            tr("Spector"),
            tr("Spell Casters"),
            tr("Spies report Roland has sent a hero to search for the Crown. If he finds it first, all is lost!"),
            tr("Spirit City"),
            tr("Spy Tower - see what your competition is doing!"),
            tr("Stairs"),
            tr("Start with five castles!  How could you lose!?  Oh yeah, everyone else starts with five, too."),
            tr("Stick to the road!"),
            tr("Stromgild"),
            tr("Stromhild"),
            tr("Stronghold"),
            tr("Stuff for red"),
            tr("Stuff for Yellow"),
            tr("Stuff For Yellow"),
            tr("Subbaculcha"),
            tr("Sundune"),
            tr("Surf and Turf"),
            tr("Swimming near the kelp is a pod of dolphins."),
            tr("Tacma"),
            tr("Tchudes"),
            tr("Teleporters"),
            tr("Terra Firma"),
            tr("Terrain Wars"),
            tr("The alliance has crumbled and all are at war. Lots of resources but little time to prepare."),
            tr("The ancient King Zealot had the artifact of the gods and then hid it in his old age so that it could not be used by others."),
            tr("The Back Door"),
            tr("The Barbarian's lands are being invaded. Are you strong enough to resist the invasion?"),
            tr("The castle of Drakonran in the east has been taken by the barbarians! Two other towns to the west have also been taken, but the barbarian armies were fairly decimated in the process."),
            tr("The center island is rumored to harbor great spells."),
            tr("The Citadel"),
            tr("The cities of the plains."),
            tr("The Clearing"),
            tr("The convoy has at long last arrived. Regretably, it has been beset by bandits on its journey here, and has far less supplies than we had hoped. Make your way south, for our spies have found rich mines there."),
            tr("The convoy should have been here by now! Let us hope that it is safe and still on its way."),
            tr("The country lords have allied and pooled their resources into one command. Not only have they massed their forces in the north, but they have sent a knight to the west to steal your supplies. Scouts report a castle to the east that would be ideal as a base of operations."),
            tr("The crew are unworthy!  I am not going down with the ship! -The Captain"),
            tr("\"The Crown\""),
            tr("The day you have feared has finally arrived.  The king, who you have faithfully served, has died, leaving no heir to his throne.  As his captain, you feel that this job should now be yours, but several factions even now are preparing for conquest.  You are at the center of the trade routes, having the sea to the south and the great forest to the north.  Go, now, Commander, and claim what is rightfully yours!"),
            tr("The diplomats who were sent here ahead of you report that the elves will only cooperate with you if you will recover the golden bow for them. It was stolen by their enemies, the Dragons and hidden behind magic barriers."),
            tr("The Eastern Town."),
            tr("The edge of the world is your edge.  But prepare to be prepared."),
            tr("The Emerald Isle"),
            tr("The Enchanted Forest."),
            tr("The End of the World is Nigh!"),
            tr("The End of the World is Nigh"),
            tr("The Epic battle against Your Rival! Eliminate everything! Total Warfare! Don't Lose your first hero!"),
            tr("The Fire King is an ally to the dragons, and will help a friend of theirs."),
            tr("The First One To Take Astircaer Wins!"),
            tr("The first piece of the artifact now lies in the hands of the Unholy Order of Warlocks. You must annihilate them, and their allies to the north. They will surely give us what we seek in exchange for their feeble lives."),
            tr("The Fortune of Infamous Uae was buried on one of these islands. She died without ever revealing it.  Find it before the other cutthroats."),
            tr("The four factions race to capture a mystical castle."),
            tr("The four spell casters face off with substantial starting armies. Can the crusaders keep the peace?"),
            tr("\"The Gauntlet\""),
            tr("The Gods have given you 6 months to prove yourself. Good or Evil - who shall prevail? (Blue,Green and Red vs Yellow, Orange and Purple)"),
            tr("The gods have granted this world a great artifact, to find it means victory."),
            tr("The Gods themselves will aid us in this War."),
            tr("The Gold Traveller's Tent is near the Aqua Taveller's Tent."),
            tr("The guardians of Dragon Isle reside in the jungle."),
            tr("The Ice Prince stands frozen in some forgotten corner of the world."),
            tr("The island...."),
            tr("The Island of Lost Reason"),
            tr("The islands have much wealth."),
            tr("The Isle of Armoria"),
            tr("The key to success is rubbing enough lamps."),
            tr("The King has declared you his hier apparent and champion. You must seek out and destroy your common enemy, Wilgatus and his Castle, Mirkosov, the source of his power."),
            tr("The King is dead, his kingdom has been shattered, and six leaders seek to seize power for themselves."),
            tr("The Kingly Wastes"),
            tr("The Kings Road."),
            tr("The King will sell you this land for 200,000 gold or you can take it by force. The choice is yours."),
            tr("The land of Heroes II."),
            tr("The Lost Castle of the Ancients"),
            tr("The mage wars have caused a great turmoil.  This island has become a central flux of magical power.  Be wary all those that enter upon here."),
            tr("The mage wars have caused great turmoil.  This island has become a central flux of magical power.  Be wary all those that enter upon here."),
            tr("The Master Merchant arrives and takes the resources he needs for trade.  Plus a little gold for expenses..."),
            tr("The Master Merchant arrives and takes the resources he needs for trading.  Plus a little more gold for expenses..."),
            tr("The Master Merchant arrives at your Castle.  He tells you tall tales of travel, full of outrageous lies.  He also gives you, your share of the profits..."),
            tr("The Master Merchant arrives back at your Castle.  He tells you tall tales of faraway places full of outrageous lies.  He also gives you, your share of the profits..."),
            tr("The Medusas have the password and they can be found just to the west."),
            tr("The more there is the less you see."),
            tr("The North Road to Roland's castle."),
            tr("The note in this bottle has become mostly indecipherable. All you can make out are references to deadly pirates, and hidden gold mines."),
            tr("The Other Side"),
            tr("The Overlord has given you 4 months to conquer this land or deliver to him the sum of 150,000 gold."),
            tr("The people on the Isle of Knowledge are taking up a collection to aid us."),
            tr("The Proving Grounds"),
            tr("The Queen's Road."),
            tr("The Realm of Air is barred, but you may appeal here for help."),
            tr("There are remnants of a mighty battle fought here, not too long ago. It looks as if whoever came this way may have made this their final stop."),
            tr("There are three enemy castles to the north. Capture them in the name of Roland the true king!"),
            tr("The Red Tide of War rolls North.  Stopping the flood seems hopeless.  Yet, Honor demands you and your ally die trying."),
            tr("There is hidden treasure north of the Green Lord's Ore Mine."),
            tr("There is hidden treasure south of the Blue Lord's Sawmill."),
            tr("There's a warm wind blowing from the south."),
            tr("There's a Wizard living in the north who is behind this peasant revolt."),
            tr("The Retreat of the Alchemist Doctor Yu"),
            tr("There used to be a mine here, but it has long since run out of ore.  You are only able to scavenge 5 units of ore from the old site."),
            tr("There was a shipreck in the far east waters recently."),
            tr("The River Styx"),
            tr("The roars of several dragons echo from the towers."),
            tr("The Rock Store."),
            tr("The Royal Gardens."),
            tr("The Scholars, Priests, and Priestesses of the Isle have given you what they can to help you against your enemies."),
            tr("The Scholars, Priests, and Priestesses of the Isle have given you what they can to help you defend against your enemies."),
            tr("These doors are a risk the likes of which you do not know."),
            tr("These lands are beholden to Lord Kraeger."),
            tr("These lands are desolate and for the most part devoid of resources. Not even the bravest heroes dare to venture into them, and plants are rare and precious here. Who knows what else awaits?"),
            tr("The Southern Witch is biding her time.  She will strike when your armies are weak."),
            tr("the stairs"),
            tr("The Table in the Great Hall of the Castle is Haunted."),
            tr("The third piece of the artifact is somewhere to the north, that much we know. We are still unsure of its exact location, but our spies are out gathering information. The forces in this area are too strong to be completely subjugated, so take what you can and hold on to it tightly."),
            tr("The troops have sworn their allegiance, but should lose a battle they will lose faith and our cause will be lost."),
            tr("The Valley of Aruk."),
            tr("The Valley of Magic holds many surprises.  You discover an old pair of boots sticking out of the sand."),
            tr("The Valley of Tresures"),
            tr("The Wasteland"),
            tr("The way of magic"),
            tr("The way of might"),
            tr("The way of numbers"),
            tr("The western town."),
            tr("The winds howl in mourning around the shipwreck."),
            tr("The wizard has an island in the southeast."),
            tr("The Wizards who have captured the Necromancers' town have wasted no time in building defenses designed to stop you, and their last castle has just been completed. Fortunately only a Captain of the Guard and a small garrison are currently present.  If you hurry, you should be able to capture the castle before they have a chance to reinforce it!"),
            tr("The wood has arrived."),
            tr("The writing on this sign is too faded to read."),
            tr("The Yellow Lord has the Ultimate Artifact."),
            tr("The Yellow Lord is a hothead who will attack before his allies can send him aid."),
            tr("They say there's mermaids in these waters..."),
            tr("This area is rich in resources. Explore, but beware, a castle left undefended will quickly fall."),
            tr("This area must be secured for the sake of the Empire. Our spies have reported a discord between The kingdom of the knights to the north, and that of the oppressive sorceresses to the northeast. Perhaps this feud can be exploited for our gain..."),
            tr("This bottle is empty."),
            tr("This is the last week you have to find the rebel wizard Joseph! Good Luck in your quest."),
            tr("This land and all others are now under the sole ownership of Ibn Fadlan, the Undead King. Any disregard for his magesty's soverign rule is to be punished by death most horrendous."),
            tr("This land has been claimed by the nation of Neroli. Interlopers are UNWELCOME."),
            tr("This rugged land will have rivals fighting the terrain as well as each other."),
            tr("This rundown village looks like it was once the epicenter of an enormous, but now ruined, city. Under a pile of rubble you find an object which looks like it has lain there for ages."),
            tr("This spot overlooks an old quarry.  This was one of the only places in the world where ore could be taken right out of the ground.  Unfortunately the jungle has reclaimed the quarry and it is unusable.  You collect the last of the ore and depart."),
            tr("This twisted maze of sorceress towns has three factions struggling for sole control.  Use your resources wisely!"),
            tr("This village appears to be in little better shape than the first one you saw. As you approach the village an old man hands you a slip of paper, with the following message, \"Joseph lives in the town of IslandHome.\""),
            tr("This village is in extremely poor shape. There is no chance of getting more than some of the lesser creatures here."),
            tr("This way to the Necromancer Forest."),
            tr("Those who seek knowledge are welcome to the city of Chronos."),
            tr("Three Warlocks in the land of Dragons. Lose thy home and all will be lost. Conquer thy enemies and the land shall forever be yours!"),
            tr("Timberhill"),
            tr("Time for a refreshing drink."),
            tr("Time is running out! The enemy's reinforcements are almost here."),
            tr("To pass you must pay troll."),
            tr("TreeHome"),
            tr("Trespassers will be EATEN!"),
            tr("Trilobar"),
            tr("Troy"),
            tr("Tundara"),
            tr("Turn back, friend, while you still can!"),
            tr("Turn Back Now!"),
            tr("Turn Back Now or all will be LOST!"),
            tr("Turn Back or DIE!"),
            tr("Turn Back or else!"),
            tr("Turn back, you fool."),
            tr("\"Turning Point\""),
            tr("Uae was the scurviest, pirate ye'd never wanta see. In all her years of murdering and thieving she amassed so much ill-gotten booty that she couldn't carry it around in her galleon.  Besides, even the meanest can't stay awake all the time.  Legend tells that she hid it so well, she was thinking that she just might forget where it was.  So she left clues around the islands, carved in stone.  Well, she's dead now.  It's up to you to recover her legacy."),
            tr("Uncle Ivan"),
            tr("Uncle Leo"),
            tr("Uncle Milty"),
            tr("Undead Armies"),
            tr("Unholy Alliance"),
            tr("Unite the Tribes. Don't lose your main hero, the first Descendant."),
            tr("Valley of Death"),
            tr("Valley Of The Damned"),
            tr("Valley of the Kings."),
            tr("Vaultius"),
            tr("Vertigo"),
            tr("Vikings!"),
            tr("Viper's Nest"),
            tr("Vulcania"),
            tr("Warrior Knight"),
            tr("Wastelands"),
            tr("Watch out for Purple!"),
            tr("Waystop"),
            tr("\"We are at the edge of the world!\"  they scream.  \"What are we doing here?\""),
            tr("Weddington"),
            tr("Weed Patch"),
            tr("We found a weakness my lord. Capture castle Black Fang and victory is ours."),
            tr("We have just learned that the artifact is on an island north of this continent. However, there does not appear to be any means to get there. Stay very alert for any possible way across the narrow channel."),
            tr("Welcome back general.  Have you finished the conquest of the northern lands?  What? you still have not finished your mission!  Get back there and teach those rebels a lesson!"),
            tr("Welcome to Li'l Alctatraz! Vistors NOT welcome."),
            tr("Welcome to Power Island. He who controls this Isle controls the Seven Lakes!"),
            tr("Welcome to the Sandbar."),
            tr("Welcome to the sandy Isle."),
            tr("Welcome to the sorceress' guild."),
            tr("Welcome to the Spiral Isles"),
            tr("Welcome to the wounderous Kitisland range.  Eruptions each day, beware of dragons."),
            tr("Welcome to Windfall Island!"),
            tr("Welcome to your DOOM!"),
            tr("We'll join you - for the right price."),
            tr("Well placed bribes have won you a stronghold near the warring Barbarians. Be advised that given their proximity an unguarded castle is an open invitation to defeat."),
            tr("Westfork"),
            tr("Westmoor"),
            tr("We told you not to drink!"),
            tr("What are you doing here?"),
            tr("What cannot be seen but only heard, and will not speak until spoken to?"),
            tr("What everyday word is most often pronounced incorrectly?"),
            tr("What goes up and down but never moves?"),
            tr("What good fortune!  You've discovered a long-abandoned settlement.  To your surprise, you discover that the previous inhabitants left some of their resources behind when they departed!"),
            tr("What is always coming but never arrives?"),
            tr("What is the Sum of all Numbers from 1 to 200?"),
            tr("What is time spent poorly?"),
            tr("What's another word for pirate treasure?"),
            tr("What's behind door number one?"),
            tr("What's this? A pile of gems?"),
            tr("What's this? Someone has left a pile of wood here!"),
            tr("What team won Super Bowl XXI and Super Bowl XXV?  (Hint... a Wizard might have these troops in his army)"),
            tr("What turns everything around but does not move?"),
            tr("What walks in the morning on four legs, two in the afternoon and three in the evening?"),
            tr("What?  What's this?  Something at the bottom of this pool..."),
            tr("When you're ready, take the teleport to the Island's Hot Spot!"),
            tr("When you think yourself invincible, walk through this gate.  Even then, prepare to meet your bitter end."),
            tr("Where am I?"),
            tr("While away seeking the Ultimate Artifact, Kastor's kingdom is invaded!"),
            tr("While traveling a mesenger meets you on the road.  His message tells of a new ally from an island far to the south.  This ally can not offer forces to your battle but has agreed to send some support in the form of gold and crystal."),
            tr("Whiteshield"),
            tr("Whittingham"),
            tr("Who am I?"),
            tr("Who am I?...  Where am I?...  Oh no! My Ship!  Well it's consigned to the ghosts of my dead crew now, at least I still have my lucky rabbits foot."),
            tr("Who is the true King?"),
            tr("\"Why have we come this way?\"  asks the first mate.  You have no answer."),
            tr("Wicked Warlock Way"),
            tr("Wilasher"),
            tr("Wildabar"),
            tr("Wilgatus"),
            tr("Willow"),
            tr("Windfall Isle"),
            tr("Winterkill"),
            tr("Winterlands"),
            tr("Witch Hunt"),
            tr("With the year long eruption of Mt. Kitisland, your three worst enemies now have a ground bridge to your eastern contenent."),
            tr("Wizardwood.  Magicians welcome!"),
            tr("Woodhaven"),
            tr("Wood's Lord"),
            tr("Woodstock"),
            tr("Woodville"),
            tr("Wormed Ash"),
            tr("Wow, somebody has left a pile of wood here!"),
            tr("Wyrm"),
            tr("Xabran"),
            tr("Yellow gets some stuff"),
            tr("Yellow's Steady Cash"),
            tr("Yellow stuff"),
            tr("Yellow's Yarbols"),
            tr("Ye old fish liver oil."),
            tr("Yorksford"),
            tr("You and your ally's families were given custody of The Isle of Knowledge.  Other Lords feel the time has come for new guardians..."),
            tr("You are a fool to come here!"),
            tr("You are fighting on the side of your king!"),
            tr("You are fighting on the side of your sister!"),
            tr("You are now entering the domain of Prince Roland. Have a nice day."),
            tr("You are now entering the domain of Prince Roland. Have a pleasant stay."),
            tr("You bribe the entrance guards of this dingy prison camp. They agree to look the other way for a little while."),
            tr("You can only reach your enemies via teleporters, but each jump is a leap of faith."),
            tr("You cautiously ride through the trees, looking out for enemy assaults, when suddenly, the old elf is beside you. \"Your quest is almost at an end, my friend. All that remains is for you to lay seige to these last few castles. The fate of my people rests upon your final battles here. May the gods be with you as well.\"  He turns to leave, but you ask him his name before he is gone. Over his shoulder, as he is leaving he says \"I am Ilthanis, king of the elves.\""),
            tr("You come across the dead remains of what was appearantly a powerful wizard!  You wonder if it's safe to continue."),
            tr("You face three opponents in this scenario. Capture their castles and their heroes to prove your worthiness to Archibald."),
            tr("You find a beautiful helm buried in the lava.  As you move to put it on your head it turns into the Hideous mask and now you realize that no creature will join you."),
            tr("You find a gleaming gold medalion buried in the  snow.  As you move to put it on it changes to the Fizbin of Misfortune."),
            tr("You find an old signpost in the midst of a thicket that reads \"Warlock Wood, West.  Barbarian Fields, East.\""),
            tr("You find a note in the bottle! It reads, \"My ship has been wrecked by the notorious pirates in this area! I am stranded on a small and barren island. Please, I beg you to come and rescue me!\""),
            tr("You found something!"),
            tr("You found Treasure!"),
            tr("You have been ordered here to claim this land in the name of your King and recover any riches that you might find.  However, five other Kings and Queens have also sent their heroes to this land, so you must watch out for them as well as the natives!"),
            tr("You have found what someone else has lost..."),
            tr("You have hired a barbarian of great power to aid you in this, your last quest. His origins are unknown to you, but you sense strong nobility beneath the furs and dirt that cover him. In addition, the famous explorer, Marco the wizard, is rumored to have wrecked his ship in this new land. Finding him would prove to be a much needed boon to your cause."),
            tr("You have just 8 weeks  to build your army and conquer a town on the other side of a distant river.  There are three paths to take, which will you choose?"),
            tr("You have just 8 weeks to build your army and conquer a town on the other side of a distant river.  There are three paths to take, which will you choose?"),
            tr("You have received a message from Archibald. \"General, these peasants deserve punishment. Put them to the sword and let Corlagon have his way with them.\""),
            tr("You have received a message from Archibald.  \" HOW DARE YOU BETRAY ME! I will see your head on the block alongside your new master's once I have won."),
            tr("You have received a message from Roland. \" I am shocked! I had thought better of you, but I was terribly wrong. Now you'll have to live with your dark decision for the rest of your life.\""),
            tr("You have recieved a shipment of supplies from your kingdom!"),
            tr("You have recieved a shipment of supplies from your kingdom! There is a note attached, \"These are all we could afford to send you from our treasuries, as the war with Harondale is taxing us greatly. We will send more in two weeks.\""),
            tr("You have six months to destroy the Necromancer Stronghold in the heart of the valley."),
            tr("You have washed up on the beach after being shipwrecked. Your goal is to find a way home."),
            tr("You hear a low rumble, look up and see an avalanche!  You dive onto a large patch of grass to avoid it.  While dusting yourself off, you consider yourself quite lucky to be alive.  Luckier still to find a Four-Leaf Clover stuck on your nose."),
            tr("You hear a rumor from a peasant who lives in the town of Waystop. He says, \"The pirates control most of the sulfur mines in this area. They use it for the cannons on their bigger boats. If you want a mine, you'll have to defeat them.\""),
            tr("You hear melodic strains of elvish music as you enter this clearing."),
            tr("You must, like, forsake your earthly wealth and, like, join us on the island of the lotus eaters."),
            tr("You must search the world for your mortal enemy, Wilgatus.  Can you find him before its too late?"),
            tr("You notice some runes hastily scrawled into a rock by your feet, They look like the initials of Uncle Ivan!"),
            tr("You notice that mines and resources in the elvish lands are few, and you send word to your kingdom that you will need extra supplies. They should respond within a fortnight."),
            tr("Your advance scouts come riding back to you with the following news. They believe they have found signs that Uncle Ivan was in this general area, and that he made his way to the north many months ago. Also they say there is a town nearby and many resources to the east."),
            tr("Your advisor approaches you, \"My liege, something must be done about these peasants! They still refuse to work.  At this rate you won't have anything to put in your daughter's dowry!\""),
            tr("Your advisor approaches you smiling greatly, \"My liege! The peasants are making money in the market, and are finally paying taxes!\""),
            tr("Your advisor approaches you with a long face, \"My liege, the peasant's numbers are growing steadily.  All they do is take, take, take! We are beginning to suffer dearly because of them.\""),
            tr("Your advisor approaches you with some startling information, \"My liege, the peasants are draining us. They do nothing, and take everything! We must get them home. Your own citizens are beginning to suffer!\""),
            tr("Your arrival here was a surprise to those sworn to guard Dragon Isle, and you were able to quickly capture one of their castles.  Use caution, though, for two other guardians remain in this jungle."),
            tr("Your castle, founded inside the center of a mile wide crater, is besieged by those who desire your mineral wealth."),
            tr("Your castle is the last outpost in the area, Don't lose it!"),
            tr("Your crew begins to grumble."),
            tr("Your crew seriously entertains thoughts of mutiny.  Your nights are sleepless."),
            tr("You're almost there!"),
            tr("You, recieve word that you have been robbed."),
            tr("You're getting colder."),
            tr("You're getting warmer."),
            tr("You're here! Oh, thank you thank you thank you! I'm in the jail east of the castle. Please hurry!"),
            tr("Your expedition has taken a turn for the worse... you now have no way to get home!"),
            tr("Your forces are thinly spread in an effort to defend all the dwarf towns (which may not be transformed into castles). Consolidate your forces and smite the enemy before the towns fall."),
            tr("Your horse stumbles and throws you from the saddle.  When you awaken you find that you have hit your head on the Fizbin of Misfortune."),
            tr("Your isolation from the rest of the kingdom has largely kept you out of the political struggles, but now with the king's death, and lack of an heir, you see a golden opportunity to seize the throne for yourself.  Just remember that you have relied largely on trade for several key resources, especially sulfur, but with a little planning this land can be yours.  Go, now, and show these peasants how to rule!"),
            tr("Your king has sent supplies to aid the war effort."),
            tr("Your opponents are allied against you and each is twice as powerful as his predecessor! Is it possible to win?"),
            tr("Your Queen sent you here to explore this newly discovered territory, but a freak storm scattered your fleet and left you stranded.  You gather the survivors and form a small settlement, naming it New Vertigo.  This place is your home now, and survival is your highest priority, but remember, if you are captured or killed, it's over!"),
            tr("Your rival, the kingdom of Harondale, is attacking your weak border towns! Recover from their first strike and crush them completely."),
            tr("Your Scouts report talking to a young knight, a squire to the two sleeping heroes.  The squire is trapped by the Aqua Magic Barriers and a group of fallen Paladins.  He says the two heroes, Dainwin and Ceallach, have awakened but are still trapped by a Gold Magical Barrier and asks your aid in freeing them."),
            tr("Your Scouts report that the Aqua Traveller's Tent is located along The North Road."),
            tr("Your scouts return with grim news.  The natives of this land are currently at war with each other, and they like outsiders even less than they like each other!  Congratulations, Commander, you're at war!"),
            tr("Your sister calls you before her altar in the morning. \"I have important news,\" she says, \"The barbarian kingdoms which border this land have agreed to lend us some of their castles and warriors in return for a share of the spoils. I hope victory comes swiftly, but your presence gives me strength to stand until whatever end awaits.\""),
            tr("Your subjects contribute to your war effort!"),
            tr("Your town is undefended and your heroes are scattered.  Do you attack or defend?"),
            tr("Your treasury has been looted by robbers and you have lost valuable resources."),
            tr("Your troops begin to wonder about your sanity."),
            tr("You run aground on the rocks and have to use some wood to fix your boat."),
            tr("You see a family of refugees making their way from the beach. You ask them about their plight and they tell you that they are from a once great city called Moss Side. They tell you that the castle was destroyed in a great conflagration, and they fled for fear of their lives."),
            tr("You see an old man bringing water towards the stables. Recognizing him as the mystic, you attempt to thank him for his gift with some gold. He refuses, but says to you instead, \"There are riddles guarding the source of the fount's power, and the dragons know the answers. Make your way through their lair, and you shall know victory.\""),
            tr("You see an old mystic perched on a rock. You walk towards him to see if he has any words for you on your quest, and he says \"First I see you as a great conquerer of the lands of men. Secondly, I see you as a mighty ruler of vast armies, well loved by your troops. Thirdly, I see you as a slayer of legions of dragons, your body bathed in their fire. Lastly, I see you standing on the shores of the fount, unable to cross.\" Then the Mystic fades away."),
            tr("You see something that could just be the elusive Nubbie!"),
            tr("You see the mast of ancient ship here.  On further investigation you find that the ships holds are full of gems.  The hours pass as your crue liberates the treasure."),
            tr("You see the remains of a burned out sawmill here.  All you can salvage is some ofwood left for scrap."),
            tr("You see the remains of an old sawmill, but it is obvious that you will not be able to make it work again."),
            tr("You see the remains of an old sawmill just to realize that it will no longer produce.  You gather the ramains and move on."),
            tr("You send this letter back to the king,\"A month has passed and we have not discovered the wizard Joseph. I only hope that we are able to locate him in time to aid us in our struggle.\""),
            tr("You should turn back."),
            tr("You stumble upon an old man who proclaims you Lord of the Realm, hands you his boots and wonders into the mountains mumbling something about being late for an important date."),
            tr("You stumple across three small rocks piled on top of each other and decide to dig undernear them.  There you find an old weather-beaten bag of gems."),
            tr("You uncover a compass in the grass!"),
            tr("You've been warned!"),
            tr("You've received a message from Roland. \"In the absence of a strong leader, the local lords have fallen to fighting. Uniting this area is critical to our cause, so we must not fail.  Leaving your castle undefended in this highly contested region will surely lead to defeat. I'm counting on you.\""),
            tr("You've received a message from the guild. \"Thank God you've arrived! We're under seige from two enemies from the north and one from across the sea. Please save us, you're our only hope.\""),
            tr("You've ruled with an iron fist (and an army of undead), but now your kingdom has turned against you!"),
            tr("You've saved a group of miners from the dragons.  One of them approaches you, \"Thank you so much for saving us!  We found this sulfer and sword in the mine, then those dragons chased us!  I don't know how much longer we could survive!\""),
            tr("You will clash quickly on this small head-to-head map, so stay on your toes!"),
            tr("You will need a stronger army than that, mortal, to step through this portal."),
    };
}
